# Generated by Django 5.1.6 on 2025-03-04 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profilepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
